language: csharp
solution: DeepClone.sln
dist: xenial
dotnet: 2.2.300
mono: none

branches:
  only:
  - master

os:
  - linux
  - osx

osx_image: xcode9.1

before_install:

#env:
  #global:
    #- DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    #- DOTNET_CLI_TELEMETRY_OPTOUT: 1


install:


script:
 - export PATH="$PATH:$HOME/.dotnet/tools"
 - dotnet tool install --global FlubuCore.GlobalTool --version 4.2.8
 - flubu Rebuild.Server -apiKey=${Nuget_Api_Key}
